"""new fields in user model

Revision ID: 647336974832
Revises: 44ca78b3f364
Create Date: 2020-06-04 18:19:10.691894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647336974832'
down_revision = '44ca78b3f364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
