"""new fields in user model

Revision ID: 783edbf3c9b9
Revises: 30b724a30159
Create Date: 2020-06-08 23:51:20.426628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783edbf3c9b9'
down_revision = '30b724a30159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unixuser', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unixuser')
    # ### end Alembic commands ###
