"""users column

Revision ID: 91d94756795b
Revises: 51330fcfe549
Create Date: 2020-06-11 22:37:13.030073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d94756795b'
down_revision = '51330fcfe549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('container', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('fullname', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('group', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('unixid', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('unixuser', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unixuser')
    op.drop_column('user', 'unixid')
    op.drop_column('user', 'group')
    op.drop_column('user', 'fullname')
    op.drop_column('user', 'container')
    # ### end Alembic commands ###
