"""new fields in user model

Revision ID: c7841f067bc1
Revises: 783edbf3c9b9
Create Date: 2020-06-08 23:57:27.313855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7841f067bc1'
down_revision = '783edbf3c9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unixid', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unixid')
    # ### end Alembic commands ###
