"""User name fields

Revision ID: e9b94561f6b4
Revises: 91d94756795b
Create Date: 2020-06-17 16:22:59.867762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b94561f6b4'
down_revision = '91d94756795b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('givenname', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    op.drop_column('user', 'givenname')
    # ### end Alembic commands ###
